spring.application.name=HorizonteDeRisco

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

server.port=${PORT:8080}

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

nasa.eonet.url=https://eonet.gsfc.nasa.gov/api/v3/events